---
- name: Configure Database servers
  hosts: databases
  become: true

  tasks:
    # - name: Install postgresql-server

    # - name: Run postgresql setup command

    # - name: Start and enable postgresql service
